export const TILE_TALLY_SOURCES = ["manual", "chat", "voice", "photo"] as const;
export type TileTallySource = (typeof TILE_TALLY_SOURCES)[number];

export const TILE_TALLY_GAME_STATUSES = ["in_progress", "complete"] as const;
export type TileTallyGameStatus = (typeof TILE_TALLY_GAME_STATUSES)[number];

export const TILE_TALLY_TURN_KINDS = ["play", "adjustment"] as const;
export type TileTallyTurnKind = (typeof TILE_TALLY_TURN_KINDS)[number];

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };

export type TileTallyPlayer = {
  id: string;
  owner_id: string;
  name: string;
  created_at: string;
};

export type TileTallyGame = {
  id: string;
  owner_id: string;
  /** Human-readable activity name. Added by the generic ledger migration. */
  title?: string | null;
  /**
   * A versioned, user-editable JSON definition for counters, event fields and
   * result fields. Preset names are hints only; the database does not restrict
   * games to a fixed list of kinds.
   */
  profile?: GameLedgerProfile | null;
  played_on: string;
  location: string | null;
  status: TileTallyGameStatus;
  source: TileTallySource;
  source_detail: JsonValue | null;
  ingest_event_id?: string | null;
  created_at: string;
  completed_at: string | null;
};

export type GameLedgerFieldType = "number" | "text" | "boolean" | "select";

export type GameLedgerField = {
  id: string;
  label: string;
  type: GameLedgerFieldType;
  required?: boolean;
  unit?: string;
  options?: string[];
  placeholder?: string;
  extra?: Record<string, JsonValue>;
};

export type GameLedgerCounter = {
  id: string;
  label: string;
  scope?: "participant" | "game";
  value_type?: "integer" | "decimal" | "duration";
  unit?: string;
  initial?: number;
  aggregation: "sum" | "latest" | "min" | "max";
  ranking?: "highest" | "lowest" | "none";
  input?: {
    mode?: "delta" | "set" | "both";
    quick_values?: number[];
    allow_negative?: boolean;
  };
  target?: {
    operator: ">=" | "<=" | "=";
    value: number;
    finish: "suggest" | "automatic";
  } | null;
  extra?: Record<string, JsonValue>;
};

/**
 * The UI understands these common fields, while `extra` and unknown JSON keys
 * make the persisted shape forward-compatible with user-defined game systems.
 */
export type GameLedgerProfile = {
  version: number;
  name: string;
  preset?: string | null;
  participant?: {
    min: number;
    max: number;
    roles?: Array<{ id: string; label: string }>;
  };
  counters: GameLedgerCounter[];
  event_fields: GameLedgerField[];
  result_fields: GameLedgerField[];
  result?: {
    mode: "derived" | "manual" | "none";
    winner_counter_id?: string;
    allow_draw?: boolean;
    allow_multiple_winners?: boolean;
  };
  tools?: string[];
  extra?: Record<string, JsonValue>;
};

export type GameLedgerEntity = {
  id: string;
  owner_id: string;
  entity_type: string;
  name: string;
  metadata: JsonValue;
  archived_at: string | null;
  created_at: string;
  updated_at: string;
};

export type GameLedgerGame = {
  id: string;
  owner_id: string;
  profile_id: string | null;
  profile_version: number | null;
  title: string;
  definition: GameLedgerProfile;
  /** `complete` is terminal; any other validated lowercase slug is an open workflow state. */
  status: string;
  location: string | null;
  started_at: string;
  ended_at: string | null;
  created_at: string;
  updated_at: string;
};

export type GameLedgerParticipant = {
  id: string;
  owner_id: string;
  game_id: string;
  entity_id: string | null;
  label: string;
  seat: number;
  metadata: JsonValue;
  created_at: string;
};

export type GameLedgerEvent = {
  id: string;
  owner_id: string;
  game_id: string;
  actor_participant_id: string | null;
  seq: number;
  event_kind: string;
  /** Arbitrary JSON payload; interpretation belongs to the game's profile. */
  event_data: JsonValue;
  note: string | null;
  occurred_at: string;
  voids_event_id: string | null;
  created_at: string;
};

export type GameLedgerMedia = {
  id: string;
  owner_id: string;
  game_id: string;
  bucket_id: string;
  storage_path: string;
  media_kind: "photo" | "video";
  mime_type: string;
  byte_size: number;
  duration_ms: number | null;
  width: number | null;
  height: number | null;
  caption: string | null;
  media_data: JsonValue;
  captured_at: string;
  created_at: string;
  deleted_at: string | null;
  /** Ephemeral signed URL generated by the client; never stored in the table. */
  signed_url?: string | null;
};

export type TileTallyGamePlayer = {
  id: string;
  owner_id: string;
  game_id: string;
  player_id: string;
  seat: number;
  created_at: string;
};

export type TileTallyTurn = {
  id: string;
  owner_id?: string;
  game_id: string;
  player_id: string;
  seq: number;
  score: number;
  word: string | null;
  is_bingo: boolean;
  kind: TileTallyTurnKind;
  source: TileTallySource;
  source_detail?: JsonValue | null;
  ingest_event_id?: string | null;
  source_item_index?: number | null;
  score_photo_id?: string | null;
  created_at: string;
};

export type TileTallyScorePhoto = {
  id: string;
  owner_id: string;
  game_id: string | null;
  storage_path: string;
  extracted_json: JsonValue | null;
  created_at: string;
};

export type TileTallyIngestEventStatus =
  | "pending"
  | "committed"
  | "rejected"
  | "answered"
  | "failed";

export type TileTallyIngestEvent = {
  id: string;
  owner_id: string;
  kind: Exclude<TileTallySource, "manual">;
  status: TileTallyIngestEventStatus;
  raw_input: string | null;
  photo_id: string | null;
  model: string | null;
  input_tokens: number | null;
  output_tokens: number | null;
  proposed_action: TileTallyPendingAction | null;
  game_id: string | null;
  created_at: string;
  committed_at?: string | null;
};

export type TileTallyAdjustmentInput = {
  player: string;
  points: number;
};

export type TileTallyTurnInput = {
  player: string;
  score: number;
  word?: string;
  is_bingo?: boolean;
};

export type TileTallyLogGamePayload = {
  played_on?: string;
  location?: string;
  players: string[];
  turns: TileTallyTurnInput[];
  adjustments?: TileTallyAdjustmentInput[];
  status: TileTallyGameStatus;
};

export type TileTallyAddTurnPayload = {
  game_ref: string;
  player: string;
  score: number;
  word?: string;
  is_bingo?: boolean;
};

export type TileTallyFinishGamePayload = {
  game_ref: string;
  adjustments?: TileTallyAdjustmentInput[];
};

export type TileTallyLogGameAction = {
  type: "log_game";
  payload: TileTallyLogGamePayload;
};

export type TileTallyAddTurnAction = {
  type: "add_turn";
  payload: TileTallyAddTurnPayload;
};

export type TileTallyFinishGameAction = {
  type: "finish_game";
  payload: TileTallyFinishGamePayload;
};

/** The exact, editable action persisted in a pending ingest event. */
export type TileTallyPendingAction =
  | TileTallyLogGameAction
  | TileTallyAddTurnAction
  | TileTallyFinishGameAction;

export type TileTallyChatMessage = {
  role: "user" | "assistant";
  content: string;
};

export type TileTallyChatRequest =
  | {
      mode?: "propose";
      source?: "chat";
      messages: TileTallyChatMessage[];
      context?: { players?: string[] };
      rawInput?: never;
    }
  | {
      mode?: "propose";
      source: "voice";
      messages: TileTallyChatMessage[];
      context?: { players?: string[] };
      rawInput: string;
    }
  | { mode: "revise"; eventId: string; action: TileTallyPendingAction }
  | { mode: "commit"; eventId: string }
  | { mode: "reject"; eventId: string };

export type TileTallyProposal = {
  reply: string;
  action?: TileTallyPendingAction;
  eventId?: string;
};

export type TileTallyListGamesFilter = {
  played_from?: string;
  played_to?: string;
  player?: string;
  status?: TileTallyGameStatus;
  limit?: number;
};

export type TileTallyListedTurn = {
  seq: number;
  player: string;
  score: number;
  word: string | null;
  is_bingo: boolean;
  kind: TileTallyTurnKind;
};

export type TileTallyListedGame = {
  id: string;
  played_on: string;
  location: string | null;
  status: TileTallyGameStatus;
  completed_at: string | null;
  players: Array<{ id: string; name: string; total: number }>;
  turns: TileTallyListedTurn[];
};

// More explicit row aliases are useful when mapping Supabase responses.
export type TileTallyPlayerRow = TileTallyPlayer;
export type TileTallyGameRow = TileTallyGame;
export type TileTallyGamePlayerRow = TileTallyGamePlayer;
export type TileTallyTurnRow = TileTallyTurn;
export type TileTallyScorePhotoRow = TileTallyScorePhoto;
