#!/usr/bin/env python3
"""Two 3D wing cases in Flow360 for the Circulation Machine:

  A. quasi2d  — the 4/40/12 section extruded, symmetry planes at BOTH ends
                (Flow360 quasi-3d farfield): the 3D solver reproducing the 2D
                physics — no spanwise gradient, no trailed vorticity.
  B. tip      — the classical half-wing: symmetry at the root, FREE tip,
                AR 8 (semispan 4c): spanwise Gamma gradient, trailed sheet,
                tip vortex.

Both cases request the full volume export (paraview format: primitiveVars,
vorticity, Q-criterion, Mach) plus pre-processed slices — five span stations
for sectional loading and five crossflow wake planes (x/c = 0.1..5 behind the
TE) where the tip-vortex roll-up lives — plus surface Cp/Cf and the spanwise
force distribution (the Gamma(y) to compare against the site's VLM).

Auth: run `flow360 configure` yourself first (never paste the key here).
Written against flow360 25.10 (introspected); smoke-test the geometry/meshing
block on a draft (draft_only=True) before a billed run.

Usage: .venv/bin/python wing_3d.py [quasi2d|tip] [--submit]
"""

import math
import sys
from pathlib import Path

HERE = Path(__file__).parent
SPAN_QUASI2D = 1.0  # one chord of span between the two symmetry planes
SEMISPAN_TIP = 4.0  # AR 8 full-wing equivalent
ALPHA_DEG = 6.0
MACH = 0.1
REYNOLDS = 1.0e6  # per chord — set thermal state / length to match

# section: same 4/40/12 four-digit family as the site (see run_case.py mirror)
from run_case import section_xy  # noqa: E402


def write_csm(case_id: str, span: float) -> Path:
    """ESP .csm: the exact site section lofted in +y. Flow360's geometry
    pipeline accepts ESP csm; the section is imported as an sketch spline."""
    xs, ys = section_xy(0.04, 0.4, 0.12, n=160)
    out = HERE / "results" / case_id
    out.mkdir(parents=True, exist_ok=True)
    csm = out / f"{case_id}.csm"
    with csm.open("w") as f:
        f.write("# generated by wing_3d.py — 4/40/12 section, unit chord\n")
        f.write("skbeg  {:.6f} 0.0 {:.6f}\n".format(xs[0], ys[0]))
        for x, y in list(zip(xs, ys))[1:]:
            f.write("   spline  {:.6f} 0.0 {:.6f}\n".format(x, y))
        f.write("skend 1\n")
        f.write(f"extrude 0 {span:.4f} 0\n")
    return csm


def build_params(fl, geometry, case_id: str, semispan: float, quasi2d: bool):
    from flow360 import u  # unit system

    te_wake_x = [1.1, 1.5, 2.0, 3.0, 6.0]  # crossflow planes, x/c from LE
    span_stations = [0.2, 0.5, 0.8, 0.95, 0.99]

    slices = [
        fl.Slice(name=f"span_y{int(100 * s)}", normal=(0, 1, 0), origin=(0.5, s * semispan, 0) * u.m)
        for s in span_stations
    ] + [
        fl.Slice(name=f"wake_x{int(10 * x)}", normal=(1, 0, 0), origin=(x, 0.5 * semispan, 0) * u.m)
        for x in te_wake_x
    ]

    farfield = fl.AutomatedFarfield(method="quasi-3d" if quasi2d else "auto")
    with fl.SI_unit_system:
        params = fl.SimulationParams(
            meshing=fl.MeshingParams(
                defaults=fl.MeshingDefaults(
                    boundary_layer_first_layer_thickness=2e-6,  # y+ < 1 at Re 1e6
                    surface_max_edge_length=0.03,
                ),
                volume_zones=[farfield],
            ),
            reference_geometry=fl.ReferenceGeometry(
                area=semispan * 1.0, moment_length=1.0, moment_center=(0.25, 0, 0)
            ),
            operating_condition=fl.AerospaceCondition.from_mach_reynolds(
                mach=MACH, reynolds_mesh_unit=REYNOLDS, alpha=ALPHA_DEG * u.deg,
                project_length_unit=1 * u.m,
            ),
            models=[
                fl.Fluid(turbulence_model_solver=fl.SpalartAllmaras()),
                fl.Wall(surfaces=[geometry["*"]]),
                fl.Freestream(surfaces=[farfield.farfield]),
                fl.SlipWall(surfaces=[farfield.symmetry_planes]),
            ],
            time_stepping=fl.Steady(max_steps=6000),
            outputs=[
                fl.VolumeOutput(
                    output_format="paraview",
                    output_fields=["primitiveVars", "vorticity", "qcriterion", "Mach"],
                ),
                fl.SliceOutput(
                    entities=slices,
                    output_format="paraview",
                    output_fields=["primitiveVars", "vorticity", "velocity", "Cp"],
                ),
                fl.SurfaceOutput(
                    surfaces=[geometry["*"]], output_format="paraview", output_fields=["Cp", "Cf", "yPlus"]
                ),
                # spanwise loading -> Gamma(y) vs the VLM
                fl.ForceDistributionOutput(name="spanwise_loading", distribution_direction=(0, 1, 0)),
            ],
        )
    return params


def main() -> int:
    which = sys.argv[1] if len(sys.argv) > 1 else "quasi2d"
    submit = "--submit" in sys.argv
    quasi2d = which == "quasi2d"
    semispan = SPAN_QUASI2D if quasi2d else SEMISPAN_TIP
    case_id = f"wing3d-{which}-a{int(ALPHA_DEG)}"

    csm = write_csm(case_id, semispan)
    print(f"[{case_id}] geometry: {csm}")

    if not submit:
        print("dry run (no submission). Re-run with --submit after `flow360 configure`.")
        return 0

    import flow360 as fl

    project = fl.Project.from_geometry(str(csm), name=f"circulation-machine {case_id}")
    geometry = project.geometry
    geometry.group_faces_by_tag("faceId")
    params = build_params(fl, geometry, case_id, semispan, quasi2d)
    case = project.run_case(params, name=case_id, draft_only=False)
    print(f"submitted: {case.id if hasattr(case, 'id') else case}")
    print("when finished: download volume/slice/surface outputs into "
          f"results/{case_id}/ and run export_results.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
