/**
 * Client access to the precomputed flexfoil viscous lattice
 * (public/flexfoil-data/lattice.json, generated by scripts/flexfoil-viscous.py).
 * The lattice covers PART of the slider space on a coarse grid; lookups snap
 * to the nearest cell and report what they snapped to — the UI must surface
 * that snap whenever it differs from the sliders.
 */

export interface ViscousMeta {
  re: number
  ncrit: number
  mach: number
  cambers: number[]
  positions: number[]
  thicknesses: number[]
  alphas: number[]
  cpAlphas: number[]
  nPanels: number
  generated: string
  solver: string
}

export interface ViscousSection {
  /** per-alpha [cl, cd, cm, xtrUpper, xtrLower], null where unconverged */
  polar: (number[] | null)[]
  cp: Record<string, { x: number[]; cp: number[] }>
}

export interface ViscousLattice {
  meta: ViscousMeta
  sections: Record<string, ViscousSection>
}

let latticePromise: Promise<ViscousLattice | null> | null = null

/**
 * Fetch the lattice once; resolves null when the data has not been generated.
 * A failed fetch is not cached, so toggling again after a network blip
 * retries instead of reporting "not generated" forever.
 */
export function loadViscousLattice(): Promise<ViscousLattice | null> {
  if (!latticePromise) {
    latticePromise = fetch('/flexfoil-data/lattice.json')
      .then((r) => (r.ok ? (r.json() as Promise<ViscousLattice>) : null))
      .catch(() => null)
      .then((result) => {
        if (!result) latticePromise = null
        return result
      })
  }
  return latticePromise
}

function nearest(values: number[], target: number): number {
  let best = values[0]
  for (const v of values) {
    if (Math.abs(v - target) < Math.abs(best - target)) best = v
  }
  return best
}

export interface ViscousLookup {
  /** the lattice cell the sliders snapped to */
  camberPct: number
  camberPosPct: number
  thicknessPct: number
  alphaDeg: number
  point: { cl: number; cd: number; cm: number; xtrU: number; xtrL: number } | null
  /** full polar of the snapped section, aligned with meta.alphas */
  polar: (number[] | null)[]
  /** surface Cp at the nearest available Cp alpha (may differ from alphaDeg) */
  cpAlphaDeg: number
  cp: { x: number[]; cp: number[] } | null
}

export function lookupViscous(
  lattice: ViscousLattice,
  camberPct: number,
  camberPosPct: number,
  thicknessPct: number,
  alphaDeg: number,
): ViscousLookup | null {
  const m = lattice.meta
  const c = nearest(m.cambers, camberPct)
  const p = nearest(m.positions, camberPosPct)
  const t = nearest(m.thicknesses, thicknessPct)
  const a = nearest(m.alphas, alphaDeg)
  const section = lattice.sections[`c${c}-p${p}-t${t}`]
  if (!section) return null

  const ai = m.alphas.indexOf(a)
  const row = ai >= 0 ? section.polar[ai] : null
  const cpA = nearest(m.cpAlphas, alphaDeg)
  const cp = section.cp[String(cpA)] ?? null

  return {
    camberPct: c,
    camberPosPct: p,
    thicknessPct: t,
    alphaDeg: a,
    point: row ? { cl: row[0], cd: row[1], cm: row[2], xtrU: row[3], xtrL: row[4] } : null,
    polar: section.polar,
    cpAlphaDeg: cpA,
    cp,
  }
}
